name: angular template asset pipeline build

on:
  push:
    branches:
      - master
env:
  TZ: Australia/Canberra

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run tests
        run: ./gradlew check

      - name: Publish the JAR to the repository
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: publish
        env:
          TRAVIS_DEPLOY_USERNAME: ${{secrets.DEPLOY_USERNAME}}
          TRAVIS_DEPLOY_PASSWORD: ${{secrets.DEPLOY_PASSWORD}}
